In [2]:
import numpy as np 

In [3]:
myarr= np.array([[3,6,2,1]], np.int64)

In [4]:
myarr[0,3]

1

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[0,3]=90

In [8]:
myarr

array([[ 3,  6,  2, 90]], dtype=int64)

In [9]:
zeros= np.zeros((2,5))

In [10]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
rng=np.arange(15)

In [12]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
lsp=np.linspace(1,100,5)

In [14]:
lsp

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [15]:
emp=np.empty((4,6))

In [16]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511018e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.29060531e-306,
        1.37961302e-306, 1.42410974e-306, 2.22522596e-306]])

In [25]:
arr=np.arange(99)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [28]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr=np.array([[1,2,3],[4,5,6],[7,1,0]])

In [30]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [31]:
arr.sum(axis=0)

array([12,  8,  9])

In [32]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [33]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [34]:
arr.flat

In [35]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [36]:
arr.ndim

2

In [37]:
arr.size

9

In [38]:
arr.nbytes

36

In [39]:
one=np.array([1,3,4,634,2])

In [40]:
one.argmax()


3

In [41]:
one.argmin()


0

In [42]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
arr.argmin()


8

In [45]:
arr.argmax()

6

In [46]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [47]:
arr.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [48]:
arr.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [49]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [50]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [51]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [43]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [52]:
arr.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [45]:
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [46]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [47]:
arr2=([[1, 4, 3],
       [4, 7, 6],
       [7, 9, 0]])

In [48]:
arr+arr2

array([[ 2,  6,  6],
       [ 8, 12, 12],
       [14, 10,  0]])

In [49]:
arr*arr2

array([[ 1,  8,  9],
       [16, 35, 36],
       [49,  9,  0]])

In [50]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [51]:
arr.min()

0

In [52]:
arr.max()

7

In [53]:
arr.sum()

29

In [54]:
type(np.where(arr>5))

tuple

In [55]:
np.where(arr>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [56]:
np.count_nonzero(arr)

8

In [57]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [58]:
arr[1,2]=0

In [59]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [60]:
import sys

In [62]:
py_ar=[0,4,55,2]

In [63]:
np_ar=np.array(py_ar)

In [64]:
sys.getsizeof(1)*len(py_ar)

112

In [65]:
np_ar.itemsize*np_ar.size

16